In [2]:
from pathlib import Path
import pandas as pd
import os

print("현재 노트북 작업경로:", os.getcwd())

SAMPLE_DIR = Path(r"C:\Users\user\ml-project\email_open\join_sample_10")

messages_path = SAMPLE_DIR / "messages_email_10.csv"
campaigns_path = SAMPLE_DIR / "campaigns_matching_10.csv"
clients_path = SAMPLE_DIR / "client_first_purchase_matching_10.csv"
holidays_path = SAMPLE_DIR / "holidays_near_message_dates_10.csv"
joined_path = SAMPLE_DIR / "joined_email_campaign_client_holiday_10.csv"

for path in [messages_path, campaigns_path, clients_path, holidays_path, joined_path]:
    print(path, "exists:", path.exists())

현재 노트북 작업경로: c:\Users\user\ml-project\email_open\join_sample_10
C:\Users\user\ml-project\email_open\join_sample_10\messages_email_10.csv exists: True
C:\Users\user\ml-project\email_open\join_sample_10\campaigns_matching_10.csv exists: True
C:\Users\user\ml-project\email_open\join_sample_10\client_first_purchase_matching_10.csv exists: True
C:\Users\user\ml-project\email_open\join_sample_10\holidays_near_message_dates_10.csv exists: True
C:\Users\user\ml-project\email_open\join_sample_10\joined_email_campaign_client_holiday_10.csv exists: True

In [3]:
messages = pd.read_csv(messages_path)
campaigns = pd.read_csv(campaigns_path)
clients = pd.read_csv(clients_path)
holidays = pd.read_csv(holidays_path)
joined_saved = pd.read_csv(joined_path)

print("messages:", messages.shape)
print("campaigns:", campaigns.shape)
print("clients:", clients.shape)
print("holidays:", holidays.shape)
print("joined_saved:", joined_saved.shape)

messages: (10, 32)
campaigns: (10, 19)
clients: (10, 2)
holidays: (7, 2)
joined_saved: (10, 18)

In [8]:
messages

,id,message_id,campaign_id,message_type,client_id,channel,category,platform,email_provider,stream,...,is_soft_bounced,soft_bounced_at,is_complained,complained_at,is_blocked,blocked_at,is_purchased,purchased_at,created_at,updated_at
0,57230833,1515915625468178372-60a4b783140cd,136,bulk,1515915625468178372,email,NaN,desktop,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,f,NaN,2023-04-29 03:40:58.956541,2023-04-29 04:23:55.506527
1,57523517,1515915625468148059-60a6172d77c81,143,bulk,1515915625468148059,email,NaN,NaN,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,f,NaN,2023-04-29 03:49:16.512635,2023-04-29 03:49:16.513507
2,58140228,1515915625501363012-60a75a86b9f64,150,bulk,1515915625501363012,email,NaN,NaN,gmail.com,desktop,...,f,NaN,f,NaN,f,NaN,f,NaN,2023-04-29 04:05:47.309875,2023-04-29 04:05:47.310476
3,59040583,1515915625491878801-60ab5a63c45a3,152,bulk,1515915625491878801,email,NaN,desktop,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,f,NaN,2023-04-29 04:33:33.422838,2023-04-29 04:33:33.424108
4,59142499,1515915625468102294-60ae233436ac4,196,bulk,1515915625468102294,email,NaN,NaN,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,f,NaN,2023-04-29 04:37:00.549254,2023-04-29 04:37:00.549978
5,59195016,1515915625471755981-60af5192878bc,230,bulk,1515915625471755981,email,NaN,NaN,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,f,NaN,2023-04-29 04:39:10.929101,2023-04-29 04:39:10.92982
6,60558895,1515915625468074529-60b9e3531c62e,289,bulk,1515915625468074529,email,NaN,NaN,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,f,NaN,2023-04-29 05:16:00.026643,2023-04-29 05:16:00.027629
7,60216533,1515915625468103044-60b8a1dce4756,296,bulk,1515915625468103044,email,NaN,NaN,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,f,NaN,2023-04-29 05:05:49.055235,2023-04-29 05:05:49.056102
8,60619013,1515915625468068328-60bde0215718b,297,bulk,1515915625468068328,email,NaN,NaN,yandex.ru,desktop,...,f,NaN,f,NaN,f,NaN,f,NaN,2023-04-29 05:19:07.949723,2023-04-29 05:19:07.950485
9,60757184,1515915625489037278-60c0983480a96,337,bulk,1515915625489037278,email,NaN,NaN,yandex.ru,desktop,...,f,NaN,f,NaN,f,NaN,f,NaN,2023-04-29 05:24:18.108919,2023-04-29 05:24:18.110505

In [9]:
campaigns

,id,campaign_type,channel,topic,started_at,finished_at,total_count,ab_test,warmup_mode,hour_limit,subject_length,subject_with_personalization,subject_with_deadline,subject_with_emoji,subject_with_bonuses,subject_with_discount,subject_with_saleout,is_test,position
0,136,bulk,email,sale out,2021-05-19 07:00:11.121170,2021-05-19 08:03:19,177363,NaN,False,NaN,133.0,False,False,True,False,False,False,NaN,NaN
1,143,bulk,email,sale out,2021-05-20 08:00:16.293566,2021-05-20 08:57:18,283063,NaN,False,NaN,112.0,False,False,True,False,False,False,NaN,NaN
2,150,bulk,email,sale out,2021-05-21 07:00:11.471804,2021-05-21 09:39:41,781354,NaN,False,NaN,133.0,False,False,True,False,False,False,NaN,NaN
3,152,bulk,email,sale out,2021-05-24 07:48:42.153896,2021-05-24 08:43:38,274633,NaN,False,NaN,109.0,False,False,True,False,False,False,NaN,NaN
4,196,bulk,email,event,2021-05-26 10:30:08.482930,2021-05-26 10:31:11,6373,NaN,False,NaN,185.0,True,False,True,False,True,False,NaN,NaN
5,230,bulk,email,sale out,2021-05-27 08:00:10.980791,2021-05-27 10:35:06,651859,NaN,False,NaN,115.0,False,False,True,False,False,False,NaN,NaN
6,289,bulk,email,sale out,2021-06-04 08:24:44.565692,2021-06-04 08:34:35,60332,NaN,False,NaN,93.0,False,False,True,False,False,False,NaN,NaN
7,296,bulk,email,sale out,2021-06-03 09:33:06.368487,2021-06-03 12:30:08,231972,NaN,False,NaN,129.0,False,False,True,False,False,True,NaN,NaN
8,297,bulk,email,sale out,2021-06-07 09:00:11.081690,2021-06-07 09:23:55,135106,NaN,False,NaN,109.0,False,False,True,False,False,False,NaN,NaN
9,337,bulk,email,event,2021-06-09 10:30:08.275903,2021-06-09 10:30:51,6582,NaN,False,NaN,106.0,False,False,True,False,False,False,NaN,NaN

In [10]:
clients

             client_id first_purchase_date
0  1515915625468068328          2022-02-07
1  1515915625468074529          2022-03-05
2  1515915625468102294          2022-02-05
3  1515915625468103044          2023-03-13
4  1515915625468148059          2021-12-17
5  1515915625468178372          2022-01-21
6  1515915625471755981          2022-12-15
7  1515915625489037278          2022-05-26
8  1515915625491878801          2022-09-13
9  1515915625501363012          2022-09-08

In [11]:
holidays

         date                         holiday
0  2021-06-12                Independence Day
1  2021-05-09                     Victory day
2  2021-05-01            Spring and Labor Day
3  2021-04-01                      Fool's day
4  2021-03-08       International Women's Day
5  2021-09-01                  Back to School
6  2021-02-23  Defender of the Fatherland Day